{% set version = "3.3.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  fn: xraylib-{{ version }}.tar.gz
  url: https://xraylib.tomschoonjans.eu/xraylib-{{ version }}.tar.gz
  sha256: a22a73b8d90eb752b034bab1a4cf6abdd81b8c7dc5020bcb22132d2ee7aacd42

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy >=0.7.0
    - cython
    - swig
    - autoconf
    - libtool
    - automake

