# Extra packages needed for CI
channels:
- conda-forge
dependencies:
  - python=3.7
  - numpy=1.15
  - hdf5
  - openmpi
  - h5py=2.10.0=mpi_openmpi*
  - mpi4py
#  - h5py=2.10.0=mpi_openmpi_py37h8f0990d_2
