{% set repo = "p39" %}

package:
  name: savu-lite
  version: {{ environ['VERSION'] }}

source:
  url: https://github.com/DiamondLightSource/Savu/archive/{{ repo }}.tar.gz

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - pip
    - wheel

  run:
    - python
    - ipython
    - numpy
    - hdf5
    - openmpi
    - h5py
    - mpi4py
    - scipy
    - pandas
    - pywavelets
    - scikit-image
    - scikit-learn
    - colorama
    - jinja2
    - pytest
    - pytest-xdist
    - mock
    - spyder
    - setuptools
    - pip
    - pynvml
    - yamllint
    - linecache2
    - traceback2
    - pyfftw
    - xraylib
    - peakutils
    - tifffile
    - pyfai
    - pymca
    - mrcfile
    - fabio

test:
  imports:
    - colorama
    - h5py
    - mpi4py
    - numpy
    - scipy
    - pyfftw
    - linecache2
    - traceback2
    - savu
    - yaml

  commands:
    - savu --version
    - savu_config -h
    - savu_quick_tests

about:
  home: https://github.com/DiamondLightSource/Savu
  license: Apache V2 and GPL V3
  license_family: GPL3
  doc_url: https://savu-lite.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/Savu/
  summary: "Savu-lite - Minimal version of Savu tomography and processing pipeline suitable for processing data on a PC"

extra:
  recipe-maintainers:
    - DaniilKazantsev
