{% set repo = "master" %}
{% set version = "3.0" %}

package:
  name: savu-lite
  version: {{ version }}

source:
  url: https://github.com/DiamondLightSource/Savu/archive/{{ repo }}.tar.gz

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  host:
    - python 3.7.5 h0371630_0
    - pip 20.3.3 pyhd8ed1ab_0
    - wheel 0.36.2 pyhd3eb1b0_0

  run:
    - python 3.7.5 h0371630_0
    - ipython
    - numpy 1.15.4 py37h8b7e671_1002
    - tomopy 1.9.1 py37h8342161_101
    - hdf5 1.10.5 mpi_openmpi_hac320be_1004
    - openmpi 4.0.2 hb1b8bf9_1
    - h5py 2.10.0 mpi_openmpi_py37h8f0990d_2
    - mpi4py 3.0.3 py37hd955b32_1
    - scipy 1.5.1 py37ha3d9a3c_0
    - pandas 1.1.3 py37h3340039_0
    - pywavelets 1.1.1 py37h03ebfcd_1
    - scikit-image 0.17.2 py37h0da4684_1
    - scikit-learn 0.23.1 py37h8a51577_0
    - geodistk 0.1.6 py37hdeaff10_0
    - morphsnakes 1.0 py37hdeaff10_0
    - tomobar 2021.02 py37hdeaff10_0
    - tomophantom 2021.02 np115py37_0
    - larix 2021.02 py37hdeaff10_0
    - ccpi-reconstruction 20.09 np115py37h3be76a2_0
    - ccpi-regulariser 2021.02 np115py37_0
    - astra-toolbox 1.9.9.dev4 py37hb48bd9c_0
    - pyfai 0.19.0 py37hb3f55d8_0
    - pymca 5.5.5 py37h03ebfcd_1
    - pyfftw 0.12.0 py37hc3ef4f8_1
    - xraylib 4.0.0 py37h539c4ae_2
    - peakutils 1.3.3 py_0
    - mrcfile 1.2.0 pyhd3deb0d_0
    - tifffile 2020.6.3 py_0
    - fabio 0.10.2 py37h03ebfcd_0
    - colorama 0.4.4 pyh9f0ad1d_0
    - jinja2 2.11.2 pyh9f0ad1d_0
    - pytest 6.2.1 py37h89c1867_0
    - setuptools 51.3.3 py37h06a4308_4
    - mock 4.0.3 py37h89c1867_0
    - spyder 4.2.0 py37h89c1867_0
    - pip 20.3.3 pyhd8ed1ab_0
    - linecache2 1.0.0 py_1
    - traceback2 1.4.0 py37_0
    - pynvml 8.0.4 py_1
    - pmacparser 4.0 py37hdeaff10_0

test:
  imports:
    - colorama
    - h5py
    - mpi4py
    - numpy
    - scipy
    - pyfftw
    - linecache2
    - traceback2
    - savu
    - yaml

  commands:
    - savu --version
    - savu_config -h
    - savu_quick_tests

about:
  home: https://github.com/DiamondLightSource/Savu
  license: Apache V2 and GPL V3
  license_family: GPL3
  doc_url: https://savu-lite.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/Savu/
  summary: "Savu-lite - Minimal version of Savu tomography and processing pipeline suitable for processing data on a PC"

extra:
  recipe-maintainers:
    - DaniilKazantsev
