package:
  name: mpi4py
  version: {{ environ['VERSION_BUILD_MPI4PY'] }}

source:
  fn: mpi4py-{{ environ['VERSION_MPI4PY'] }}.tar.gz
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-{{ environ['VERSION_MPI4PY'] }}.tar.gz

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  files:
    - mpiexec.sh
    - helloworld.py
  script: run_test.sh

build:
  preserve_egg_dir: False
  number: 0

about:
  home: https://mpi4py.bitbucket.io/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
