name: root
channels:
- local
- defaults
- conda-forge
- dkazanc
- ccpi
- astra-toolbox/label/dev
dependencies:
- cython
- spyder
- scipy
- pytest
- colorama
- setuptools
- jinja2
- numpy
- pandas
- mock
- ipython
- matplotlib
- PyWavelets
- scikit-image
- scikit-learn
- tomobar
- tomophantom
- ccpi-regulariser
- larix
- ccpi-reconstruction
- astra-toolbox
- xraylib
- tomopy
- pyfai
- fabio
- pymca
- tifffile
- pyfftw
- PeakUtils
- pip
- yamllint
- pip:
  - pyreadline
  - nvidia-ml-py
  - pmacparser
  - gnureadline==6.3.8
  - sphinx-rtd-theme
