{% set CIL_VERSION = "1.4.7" %}

package:
  name: tomophantom
  version: {{ CIL_VERSION }}

source:
  url: https://github.com/dkazanc/TomoPhantom/archive/v{{ CIL_VERSION }}.tar.gz


build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - CIL_VERSION={{ CIL_VERSION }}

requirements:
  build:
    - python
    - numpy
    - setuptools
    - cython
    - cmake
    - blas=*=openblas # [not win]


  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python
    - numpy
    - libgcc-ng # [unix]

about:
  home: https://github.com/dkazanc/TomoPhantom
  license:  Apache 2.0 license
  summary: 'Tomography Phantom Data generator'
