package:
  name: mpi4py
  version: {{ environ['VERSION_MPI4PI'] }}

source:
  fn: mpi4py-{{ environ['VERSION_MPI4PI'] }}.tar.gz
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-{{ environ['VERSION_MPI4PI'] }}.tar.gz

build:
  number: 0
  script: env MPICC=$MPICC $PYTHON -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openmpi 3.1.4 hc99cbb1_0
    - setuptools
  run:
    - python
    - openmpi 3.1.4 hc99cbb1_0

test:
  files:
    - mpiexec.sh
    - helloworld.py
  script: run_test.sh

about:
  home: https://mpi4py.bitbucket.io/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for MPI
  description: |
     MPI for Python provides bindings of the Message Passing Interface (MPI)
     standard for the Python programming language, allowing any Python program
     to exploit multiple processors.
  doc_url: https://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - msarahan
    - ocefpaf
