{% set repo = "local_repo" %}

package:
  name: savu
  version: "local_repo"

source:
  path: /home/qmm55171/Documents/Git/git_repos/Savu

requirements:
  build:
    - python

build:
  preserve_egg_dir: True
  number: 0
  script_env:
    - FACILITY

about:
  home: https://github.com/diamondlightsource/Savu
  license: Apache V2 and GPL V3
  license_file: LICENCE.txt

