{% set repo = "master" %}

package:
  name: savu
  version: "master"

source:
  url: https://github.com/DiamondLightSource/Savu/archive/{{ repo }}.tar.gz

requirements:
  build:
    - python

build:
  preserve_egg_dir: True
  number: 0
  script_env:
    - FACILITY

about:
  home: https://github.com/diamondlightsource/Savu
  license: Apache V2 and GPL V3
  license_file: LICENCE.txt

