{% set version = "2.10.0" %} # change this

package:
  name: h5py
  version: {{ version }}

source:
  fn: h5py-{{ version }}.tar.gz
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
requirements:
  build:
    - python
    - numpy
    - hdf5
    - cython
    - pkgconfig
    - six

build:
  number: 1

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)

