package:
  name: astra-toolbox
  version: '1.9.9dev'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  git_tag: master

build:
  number: 0
  script_env:
    - CC # [linux]

requirements:
  build:
    - python
    - numpy
    - cython >=0.13
    - nomkl # [not win]
    - scipy
    - cudatoolkit >=10.1
    - six

run:
    - python
    - numpy
    - scipy
    - six
    - libastra ==1.9.9dev

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'
