{% set version = "1.10.5" %}
{% set release = "hdf5-1.10" %}
{% set patch = "hdf5-1.10.5" %}

package:
  name: hdf5
  version: {{ version }}

source:
  fn: {{ patch }}.tar.bz2
  url: https://www.hdfgroup.org/ftp/HDF5/releases/{{ release }}/{{ patch }}/src/{{ patch }}.tar.bz2
  md5: 7c19d6b81ee2a3ba7d36f6922b2f90d3

build:
  number: 1

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)

