package:
  name: xdesign
  version: '0.3.0'

source:
  git_url: https://github.com/tomography/xdesign.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

about:
  home: http://xdesign.readthedocs.io
  license: BSD-3
  summary: 'Benchmarking and optimization tools for tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

