#!/bin/bash

#$ -l h_rt=00:01:00
#$ -N SavuDeps.mpi4py
#$ -pe openmpi 10
#$ -cwd
#$ -P tomography

module purge
module load openmpi/3.1.3

#IMAGE=$(/dls_sw/apps/python/anaconda/4.6.14/64/envs/python3.7/bin/sregistry get savu/deps)
IMAGE=/dls/tmp/awf63395/singularity/shub/savu-deps-latest.sif

#export OMPI_MCA_btl=openib,self

mpirun -v -np ${NSLOTS} singularity exec -B /dls/tmp/awf63395 ${IMAGE} python SavuDeps.mpi4py.py
