package:
  name: h5py
  version: {{ environ['VERSION_H5PY'] }}

source:
  fn: h5py-{{ environ['VERSION_H5PY'] }}.tar.gz
  url: https://github.com/h5py/h5py/archive/{{ environ['VERSION_H5PY'] }}.tar.gz

requirements:
  build:
    - python
    - numpy
    - hdf5 1.10.5_openmpi3.1.4
    - cython
    - pkgconfig
    - six

build:
  number: 1

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)
