name: conda

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # 18.04 supports CUDA 10.1+ (gxx <= 8)
          - os: ubuntu-18.04
            cuda: "10.1"
            gcc: 8
          # 16.04 supports CUDA 8+
          #- os: ubuntu-16.04
          #  cuda: "10.1"
          #  gcc: 7
          #- os: ubuntu-16.04
          #  cuda: "9.2"
          #  gcc: 7
          #- os: ubuntu-16.04
          #  cuda: "9.1"
          #  gcc: 6
      max-parallel: 5
    env:
      build_dir: "build"
      config: "Release"
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 4.6.14
        activate-environment: savu
        python-version: 3.7
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Building savu-lite
      shell: bash -l {0}
      run: |
        rm -rf ~/.condarc
        conda config --add channels defaults
        conda config --append channels conda-forge
        conda config --append channels astra-toolbox/label/dev
        conda config --append channels ccpi
        conda config --append channels dkazanc
        conda config --set anaconda_upload no
        conda config --set channel_priority flexible
        conda config --set auto_activate_base false
        conda config --set show_channel_urls true
        conda install --yes conda-build anaconda-client setuptools
        conda info
        python --version
        cd ./install/savu_lite37/
        conda build .

    - name: Run savu savu_full_tests
      shell: bash -l {0}
      run: |
        conda activate /usr/share/miniconda3/envs/savu
        savu_full_tests

    - name: Decrypt a secret
      run: ./install/savu_lite37/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Uploading savu-lite package to conda with dev label
      run: |
        conda install --yes conda-build anaconda-client
        chmod +x ./install/savu_lite37/scripts/conda_upload.sh
        ./install/savu_lite37/scripts/conda_upload.sh
