name: savu-build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
      max-parallel: 5
    env:
      build_dir: "build"
      config: "Release"
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: savu_lite
        python-version: 3.7
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Building savu-lite
      shell: bash -l {0}
      run: |
        rm -rf ~/.condarc
        conda config --add channels defaults
        conda config --append channels conda-forge
        conda config --append channels astra-toolbox/label/dev
        conda config --append channels ccpi
        conda config --append channels savu-dep
        conda config --set anaconda_upload no
        conda config --set channel_priority flexible
        conda config --set auto_activate_base false
        conda config --set show_channel_urls true
        conda install --yes conda-build anaconda-client setuptools
        conda info
        python --version
        cd ./install/savu_lite37/condabuild/
        conda build .

    - name: Decrypt a secret
      run: ./install/savu_lite37/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    - name: Uploading savu-lite package to conda with dev label
      run: |
        conda install --yes conda-build anaconda-client
        chmod +x ./install/savu_lite37/scripts/conda_upload.sh
        ./install/savu_lite37/scripts/conda_upload.sh

    - name: Install dev-savu and run savu_full_tests
      shell: bash -l {0}
      run: |
        conda activate /usr/share/miniconda3/envs/savu_lite
        conda install --yes -c savu-dep/label/dev savu-lite
        savu_full_tests
