name: wemakepython

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - uses: wemake-services/wemake-python-styleguide@master
